version: '3'

services:
    test-app:
        build: './app'
        ports:
            - 7654:7654
        command: ./wait-for-it.sh db:5432 -- python test.py

    db:
        image: 'postgres:13-alpine'
        environment:
            POSTGRES_DB: 'the_db'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'the_pass'
        expose:
            - 5432
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data: